version: '3.8'

services:
  pact-broker:
    image: pactfoundation/pact-broker:latest
    ports:
      - "9292:9292"
    environment:
      PACT_BROKER_DATABASE_USERNAME: pactbroker
      PACT_BROKER_DATABASE_PASSWORD: password
      PACT_BROKER_DATABASE_HOST: db
      PACT_BROKER_DATABASE_NAME: pactbroker
      PACT_BROKER_DATABASE_ADAPTER: postgres
    depends_on:
      - db

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: pactbroker
      POSTGRES_PASSWORD: password
      POSTGRES_DB: pactbroker
    ports:
      - "5432:5432"